import CartSidebar from "@/components/CartSidebar";
import { ToastProvider } from "@/contexts/ToastContext";
import AuthProvider from "@/providers/AuthProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ToastProvider>
            <AuthProvider>{children}</AuthProvider>
            <CartSidebar />
          </ToastProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
